candyprj/boardapp/urls.py
from django.urls import path
from . import views

app_name = 'boardapp'
urlpatterns = [

    path('main/', views.main, name = 'main'),
    path('board/', views.board, name ='board'),
    path('home/', views.home, name='home'),
    # path('search/', views.search),

    #스터디 모집 게시판
    path('', views.index, name='index'),
    path('<int:postNum>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:postNum>/create_reply/', views.create_reply, name='create_reply'),
    path('<int:board_id>/update/', views.update, name ='update'),
    path('<int:board_id>/delete/', views.delete, name ='delete'),

    #공유 게시판
    path('sharedetail/<int:topicid>/', views.sharedetail, name='sharedetail'),
    # path('<int:board_id>/update1/', views.update1, name ='update1'),
    # path('<int:board_id>/delete1/', views.delete1, name ='delete1'),
    # path('<int:writter>/create1_reply/', views.create1_reply, name='create1_reply'),
    # path('<int:id>/', views.detail1, name='detail1'),
    path('new/new_write/' , views.new_write, name='new_write'), 
    
    # path('download/<id>', views.download, name = 'download'),
    # path('filedelete/<id>', views.file_delete, name ='file_delete'),
    
    path('sharedetail/<int:topicid>/', views.sharedetail, name='sharedetail'),
    path('sharedetail1/<int:postid>/', views.sharedetail1, name='sharedetail1'),
    path('main/', views.main, name = 'main'),
    path('board/', views.board, name ='board'),
    path('home/', views.home, name='home'),

    path('share/',views.share, name = 'share'),
    path('new/' , views.new_topic, name='new_topic'), #게시글 작성 페이지 url 추가 board/new/ ?
    path('replys/' , views.new_replys, name='replys'), 
]

candyprj/candyprj/urls.py
from http.client import ImproperConnectionState
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#신규작성
# from boardapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('boardapp.urls')),
    path('user/', include('userapp.urls')),
    # path('board/new/' , views.new_topic, name='new_topoc'), #게시글 작성 페이지 url 추가 board/new/ ?
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

candyprj/userapp/urls.py
from django.urls import path
from . import views


app_name = 'userapp'
urlpatterns = [
     path('signup/', views.signup, name='signup'),
     path('profile/', views.profile, name='profile'),
     path('update/', views.update, name='update'),
     path('login/', views.login, name='login'),
     path('logout/', views.logout, name='logout'),
     path('<str:id>/', views.userinfo, name='userinfo'),
     # path('img_show/', views.img_show, name='img_show'),
]

candyprj/userapp/models.py
from django.db import models
# Create your models here.
class User(models.Model):
    '''
    id : 회원아이디(PK)
    pw : 비밀번호
    name : 이름
    birth : 생년월일
    mail : 이메일
    reportCnt : 신고누적횟수
    '''
    id = models.CharField(max_length=20 ,primary_key=True)
    pw = models.CharField(max_length=45)
    name = models.CharField(max_length=45)
    birth = models.CharField(max_length=45)
    mail = models.CharField(max_length=45)
    reportCnt = models.IntegerField(default=0)
    file = models.FileField(upload_to='%Y/%m/%d')

candyprj/userapp/views.py
from audioop import reverse
from django.forms import NullBooleanField
from django.shortcuts import render,redirect
from numpy import empty
from sqlalchemy import null
from .models import User
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib import messages

def signup(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        pw = request.POST.get('pw')
        name = request.POST.get('name')
        birth = request.POST.get('birth')
        mail = request.POST.get('mail')
        m = User(id=id, pw=pw, name=name, birth=birth, mail=mail)
        m.save()

        return redirect('../../user/login')     

    else:
        return render(request, 'userapp/signup.html')


def profile(request):
    # profile = User.objects.get(id = 'abc')
    id = request.session.get('id')
    profile = User.objects.get(id = id)
    return render(request, 'userapp/profile.html',{'profile':profile})


def update(request):
    id = request.session.get('id')
    update = User.objects.get(id = id)
    new = User.objects.get(id = id)
    if request.method == "POST":

        update.file = request.FILES.get('file') 
        if update.file == None:
            update.file = new.file
        else :
            update.file = update.file
        
        update.pw = request.POST.get('pw')
        if update.pw =='':
            update.pw = new.pw
        else :
            update.pw = update.pw
        
        update.name = request.POST.get('name')
        if update.name =='':
            update.name = new.name
        else :
            update.name = update.name
        
        update.birth = request.POST.get('birth')
        if update.birth =='':
            update.birth = new.birth
        else :
            update.birth = update.birth

        update.mail = request.POST.get('mail')
        if update.mail =='':
            update.mail = new.mail
        else :
            update.mail = update.mail
        
       
        update.save()


        return render(request, 'userapp/new_profile.html')

    else:
        return render(request, 'userapp/update.html', {'update':update,'new':new})

# def img_show(request):
#     id = request.session.get('id')
#     image = User.objects.get(id = id)
#     uploadFile = image.objects.get(id=id)
#     return render(
#         request, 'userapp/profile.html',
#         {'uploadFile': uploadFile})


def login(request):
    
    if request.method == 'POST':
        id = request.POST.get('id')
        pw = request.POST.get('pw')
        try:
            m = User.objects.get(id=id, pw=pw)
        except User.DoesNotExist as e:
            messages.add_message(request, messages.INFO, '아이디 비밀번호를 확인하세요!')
            return render(request, 'userapp/login.html')

        else:
            request.session['id'] = m.id
            request.session['name'] = m.name
            
        return redirect('../../board/home')
    else:
        return render(request, 'userapp/login.html')


def logout(request):
    # del request.session['id'] # 개별 삭제
    # del request.session['name'] # 개별 삭제
    request.session.flush() # 전체 삭제
    # return render(request,'boardapp/main.html')
    return redirect('../../board/main')


# def profile(request):
#     id = request.session.get('id')
#     profile = User.objects.get(id = id)
#     return render(request, 'userapp/profile.html',{'profile':profile})

def userinfo(request, id):
    user = User.objects.get(id=id)

    return render(request, 'userapp/profile.html',{'profile':user})

candyprj/templates/userapp/login.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<div class="container">
	<div class="row mt-5">
		<div class="col-8" text-center>
			<h2>로그인</h2>
		</div>
	</div>
	<div class="row mt-5">
		<div class="col-8">
			<form method="post" >
				{% csrf_token %}
				아이디 : <input type="text" class="form-control" name="id"><br>
				비밀번호 : <input type="password" class="form-control" name="pw"><br>
				<input type="submit" class="form-control" value="로그인">  
			</form>
			<button id = 'signupBtn' class="form-control" onclick="location.href='/user/signup'">회원가입</button>
			{% if messages %}
				{% for message in messages %}
					
					{{ message.message }}
				{% endfor %}
			{% endif %}
		</div>
	</div>
	
</div>

{% endblock  %}

candyprj/templates/userapp/new_profile.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<h2>마이페이지</h2>
<hr>
{% load static %}




<div class="container-fluid mt-5">
  <div class="row">
    <div class="card col-lg-6 offset-lg-3 mb-3">
      <div class="row" >
        
        

        <div class="card-body" >
            <table style="color:black; margin-left:10px;">
                <tr>
                    <div style="text-align: center;">
                        <h1>수정이 완료되었습니다.</h1>
                    </div>
                </tr>
                
                
            </table>

            <hr>
            <div style="text-align: center;">
            <!-- <div style="margin-left: 10px;"> -->
                
                <a href="{% url 'userapp:profile' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;프로필</a>
                /
                <a href="{% url 'boardapp:home' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;home</a> <br>
            </div>
      </div>
    </div>
  </div>
</div>

{% endblock  %}





{% comment %} {% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<h2>마이페이지</h2>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
</head>
<body>
    <h1>My page</h1>

    <h1>수정이 완료되었습니다.</h1>
    
    <button id='updateBtn' type="button" onclick="location.href='/user/profile/'">프로필</button>
    <button id='updateBtn' type="button" onclick="location.href='/board/home/'">홈으로</button>
</body>
</html>

{% endblock  %} {% endcomment %}

candyprj/templates/userapp/profile.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<h2>마이페이지</h2>
<HR ALIGN= WIDTH= SIZE=>
{% load static %}

{% block head_title %}{{ profile.name }} | Mypage {% endblock head_title %}


<style>
.round {
    width="200";
    height='200';
    border-radius: 50%;
}
</style>
<div class="container-fluid mt-5">
  <div class="row">
    <div class="card col-lg-6 offset-lg-3 mb-3">
      <div class="row" >
        {% if profile.file == "" %}
        <img class="round" src="{%static 'image/profile.jpg'%}" width="200" >
        {% else %}
        <img class="round" src="{{ profile.file.url }}" width="200" height='200' >
        {% endif %}
        

        <div class="card-body" >
            <table style="color:black; margin-left:10px;">
                <tr>
                    <td class="profile_title">아이디</td>
                    <td class="profile_content"> : {{profile.id }}</td>
                    
                </tr>
                {% comment %} 비밀번호 조회기능 삭제 {% endcomment %}
                <tr>
                    <td class="profile_title">이름</td>
                    <td class="profile_content"> : {{ profile.name }}</td>
                </tr>
                <tr>
                    <td class="profile_title">메일</td>
                    <td class="profile_content"> : {{ profile.mail }}</td>
                </tr>
                
            </table>

            <hr>
            <div style="text-align: center;">
            <!-- <div style="margin-left: 10px;"> -->
                {%if request.session.id == profile.id%}
                <a href="{% url 'userapp:update' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-edit"></i>&nbsp;프로필 수정</a>&nbsp;&middot;&nbsp;
                {%endif%}
                <a href="{% url 'boardapp:home' %}" style="color:#d14040f2; font-size:15px;"><i class="fas fa-user-slash"></i>&nbsp;home</a> <br>
            </div>
      </div>
    </div>
  </div>
</div>

{% endblock  %}

candyprj/templates/userapp/signup.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>

<div class="container">
    <div class="row mt-5">
        <div class="col-8" text-center>
            <h2>회원가입</h2>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-8">
            <form method="post">
                {% csrf_token %}
                아이디 : <input type="text" class="form-control" name="id"><br><br>
                비밀번호 : <input type="text" class="form-control" name="pw"><br><br>
                이름 : <input type="text" class="form-control" name="name"><br><br>
                생일 : <input type="text" class="form-control" name="birth"><br><br>
                메일 : <input type="text" class="form-control" name="mail"><br><br>
                <button id='signupBtn' class="from-control" onclick="signup()"  >회원가입</button>
            </form>
        </div>
    </div>
</div>


<script>
    function signup(){

        alert("회원가입되었습니다.")
    }
</script>
{% endblock  %}

candyprj/templates/userapp/update.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<h2>마이페이지</h2>
<HR ALIGN= WIDTH= SIZE=>
{% load static %}

{% block head_title %}<font size = "3">프로필 수정</font> {% endblock head_title %}


<style>
.round {
    border-radius: 50%;
}
</style>
<div class="container-fluid mt-4">
  <div class="row">
    <div class="card col-lg-4 offset-lg-4 mb-3">
      <div class="row" >

        

        <div class="card-body" >
            <table style="color:black; margin-left:10px;">
                <form action="{% url 'userapp:update' %}" method="post"
                enctype="multipart/form-data">
                    
                    {% csrf_token %}
                    <tr>
                    <tb><font size = "6"> 아이디 : {{update.id}}</font></tb><br>
                    <hr>
                    <tb><b> 프로필 이미지 변경 : <b/></tb><br>
                    <input type="file" name="file"><br>
                    <br>
                    <tb><b>현재 비밀번호 : {{update.pw}}</b></tb><br>
                    비밀번호 : <input type="text" name="pw"><br>
                    <tb><b>현재 이름 : {{update.name}}</b></tb><br>
                    이름 : <input type="text" name="name"><br>
                    <tb><b>생일 :{{update.birth}}</b></tb><br>
                    생일 : <input type="text" name="birth"><br>
                    <tb><b>현재 메일 : {{update.mail}}</b></tb><br>    
                    메일 : <input type="text" name="mail"><br>
                    </tr>
                    <br>
                    <button id='updateBtn' type="submit">수정완료</button>
                    <button id='updateBtn' type="button" onclick="location.href='/user/profile/'">취소</button>
                </form>
            </table>

            <hr>
            {% comment %} <div style="text-align: center;">
            <!-- <div style="margin-left: 10px;"> -->
                
            </div> {% endcomment %}
      </div>
    </div>
  </div>
</div>

{% endblock  %}




{% comment %} {% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<h2>프로필 수정</h2>
<form action="{% url 'userapp:update' %}" method="post"
enctype="multipart/form-data">

    {% csrf_token %}
    <h1> 아이디 : {{update.id}}</h1>
    <h1> 프로필 이미지 변경 : </h1>
    <input type="file" name="file">
    <h1>현재 비밀번호 : {{update.pw}}</h1>
    비밀번호 : <input type="text" name="pw"><br>
    <h1>현재 이름 :{{update.name}}</h1>
    이름 : <input type="text" name="name"><br>
    <h1>생일 :{{update.birth}}</h1>
    생일 : <input type="text" name="birth"><br>
    <h1>현재 메일 : {{update.mail}}</h1>    
    메일 : <input type="text" name="mail"><br>
    <button id='updateBtn' type="submit">수정완료</button>
    
</form>

<button id='updateBtn' type="button" onclick="location.href='/user/profile/'">취소</button>
{% endblock  %} {% endcomment %}