candyprj/boardapp/urls.py
from django.urls import path
from . import views

app_name = 'boardapp'
urlpatterns = [

    path('main/', views.main, name = 'main'),
    path('board/', views.board, name ='board'),
    path('home/', views.home, name='home'),
    # path('search/', views.search),

    #스터디 모집 게시판
    path('', views.index, name='index'),
    path('<int:postNum>/', views.detail, name='detail'),
    path('write/', views.write, name='write'),
    path('write/write_board', views.write_board, name='write_board'),
    path('<int:postNum>/create_reply/', views.create_reply, name='create_reply'),
    path('<int:board_id>/update/', views.update, name ='update'),
    path('<int:board_id>/delete/', views.delete, name ='delete'),

    #공유 게시판
    path('sharedetail/<int:topicid>/', views.sharedetail, name='sharedetail'),
    # path('<int:board_id>/update1/', views.update1, name ='update1'),
    # path('<int:board_id>/delete1/', views.delete1, name ='delete1'),
    # path('<int:writter>/create1_reply/', views.create1_reply, name='create1_reply'),
    # path('<int:id>/', views.detail1, name='detail1'),
    path('new/new_write/' , views.new_write, name='new_write'), 
    
    # path('download/<id>', views.download, name = 'download'),
    # path('filedelete/<id>', views.file_delete, name ='file_delete'),
    
    path('sharedetail/<int:topicid>/', views.sharedetail, name='sharedetail'),
    path('sharedetail1/<int:postid>/', views.sharedetail1, name='sharedetail1'),
    path('main/', views.main, name = 'main'),
    path('board/', views.board, name ='board'),
    path('home/', views.home, name='home'),

    path('share/',views.share, name = 'share'),
    path('new/' , views.new_topic, name='new_topic'), #게시글 작성 페이지 url 추가 board/new/ ?
    path('replys/' , views.new_replys, name='replys'), 
]

candyprj/candyprj/urls.py
from http.client import ImproperConnectionState
from xml.dom.minidom import Document
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#신규작성
# from boardapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('boardapp.urls')),
    path('user/', include('userapp.urls')),
    # path('board/new/' , views.new_topic, name='new_topoc'), #게시글 작성 페이지 url 추가 board/new/ ?
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

candyprj/userapp/urls.py
from django.urls import path
from . import views


app_name = 'userapp'
urlpatterns = [
     path('signup/', views.signup, name='signup'),
     path('profile/', views.profile, name='profile'),
     path('update/', views.update, name='update'),
     path('login/', views.login, name='login'),
     path('logout/', views.logout, name='logout'),
     path('<str:id>/', views.userinfo, name='userinfo'),
     # path('img_show/', views.img_show, name='img_show'),
]

candyprj/boardapp/models.py
from django.db import models
from sqlalchemy import ForeignKey
from userapp.models import User
# Create your models here.
class Board(models.Model):
    '''
    postNum : 게시글번호(PK)
    title : 제목
    content : 내용
    id : 작성자 (FK)
    pub_date : 배포일
    imgfile : 이미지파일
    '''
    postNum = models.AutoField(primary_key=True)
    id = models.ForeignKey("userapp.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length= 1000)
    pub_date = models.DateTimeField()
    def __str__(self):
        return self.title
        
class Reply(models.Model):
    '''
    repNum : 댓글번호(PK)
    postNum : 게시글번호(FK)
    id : 작성자(FK)
    comment : 댓글내용
    rep_date : 작성일
    '''
    repNum = models.AutoField(primary_key=True)
    postNum = models.ForeignKey(Board, on_delete=models.CASCADE)
    id = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=200)
    rep_date = models.DateTimeField()

    def __str__(self):
        return self.comment, self.id


#########################################################기업별 면접 공유 게시판

class Topic(models.Model):
    postNum = models.AutoField(primary_key=True)
    id = models.ForeignKey("userapp.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length= 1000)
    pub_date = models.DateTimeField()
    def __str__(self):
        return self.title

class Replys(models.Model):
    '''
    message 댓글내용
    created_at -댓글 작성일시
    created_by 댓글 쓴사람
    updated at 댓글 수정일시
    updated by 댓글 수정한사람
    
    '''
    message = models.TextField(max_length=5000)
    created_at = models.DateTimeField(auto_now=True)
    created_by= models.ForeignKey("userapp.User", null=True, related_name='posts',on_delete=models.CASCADE)
    updated_at = models.DateField(null = True)
    updated_by=  models.ForeignKey("userapp.User",null=True,related_name='+',on_delete=models.CASCADE)
    # topic = models.ForeingKey('Topic')

    # topic =  Otpic.objexts.get(id=topicid)
    # replies  = topic.repliy_set.all()
    # render (template, { topic, replies})

    # {% for r in replies %}
    #     {{r.body}}
    # {%endfor %}

candyprj/boardapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.utils import timezone
from django.urls import reverse
from django.core.paginator import Paginator
from matplotlib.pyplot import title
from userapp.models import User

from .models import Board, Topic, Replys

# from userapp.views import ss

#기본페이지
# def index(request):
#     return render(request, 'boardapp/index.html', {'title':'data'})

def home(request):
    # all_boards = Board.objects.order_by('-pub_date')
    kw = request.GET.get('kw', '')  # 검색어
    all_boards = Board.objects.filter(title__contains=kw).order_by('-postNum')
    paginator = Paginator(all_boards, 10)
    page = request.GET.get('page','1')
    board_list = paginator.get_page(page)
    context={'all_boards':board_list}


    return render(request, 'boardapp/home.html', {'board': board_list, 'kw':kw})



def board(request):
    return render(request, 'boardapp/board.html', {'title':'board'})  


#######################################################################

def index(request): #게시글 목록
    all_boards = Board.objects.all()
    paginator = Paginator(all_boards, 10)
    page = int(request.GET.get('page',1))
    board_list = paginator.get_page(page)

    board = Board.objects.all().order_by('-postNum')[:5]
    
    return render(request, 'boardapp/index.html', {'title':'Board List', 'board_list': board_list, 'board':board})

def detail(request, postNum): #게시글 제목 선택시 상세 페이지로 이동
    board = Board.objects.get(postNum=postNum)
    return render(request, 'boardapp/detail.html', {'boardapp': board})

def write(request): #게시글 목록에서 글쓰기 버튼 클릭 시 쓰기 페이지로 이동
    return render(request, 'boardapp/write.html')

def write_board(request): #쓰기 페이지에서 글 등록시 submit 처리
    # uid = ss.GET.get('ses_id')
    uid = request.session['id']
    uid = User.objects.get(id = uid)


    b = Board(id = uid,title=request.POST['title'], content=request.POST['detail'], 
    pub_date=timezone.now()) #recuritment --> 필요없다. 조회할때만 모집중인지 아닌지 버튼으로 ex 좋아요, 싫어요
    if b.title != "": #제목이 입력된 경우에만 저장
        b.save()

    return HttpResponseRedirect(reverse('boardapp:home'))

def create_reply(request, postNum): # 상세 페이지에서 댓글 동록시 submit 처리
    uid = request.session['id']
    uid = User.objects.get(id=uid)

    b = Board.objects.get(postNum = postNum)
    b.reply_set.create(id = uid, comment=request.POST['comment'], rep_date=timezone.now())
    return HttpResponseRedirect(reverse('boardapp:detail', args=(postNum,)))  

def main(request):
    return render(request,'boardapp/main.html')

def update(request, board_id):
    b = Board.objects.get(postNum= board_id)
    temp = Board.objects.get(postNum= board_id)
    if request.method == "POST":
        b.title=request.POST['title']
        if b.title == "":
            b.title = temp.title
        b.content=request.POST['detail']
        if b.content == "":
            b.content = temp.content
        b.pub_date=timezone.now()
        b.save()
        return HttpResponseRedirect(reverse('boardapp:detail',args=(board_id,)))
    else:
        b=Board
        return render(request, 'boardapp/update.html', {'boardapp':b})

def delete(request, board_id):
    b = Board.objects.get(postNum=board_id)
    b.delete()
    return redirect('boardapp:home')



######################################################################기업별 면접공유 함수
from .models import Topic, Replys
from django.http import HttpResponse

def share(request):
    topics = Topic.objects.all()
    return render(request,'boardapp/share.html',{'topics':topics})
    #share html을 렌더링하고 topics 개체 반환

def sharedetail(request, topicid):
    uid = request.session['id']
    uid = User.objects.get(id = uid)
    topics = get_object_or_404(Topic, pk=topicid)
    try:
        uid = request.session['id']
        session = User.objects.get(id = uid)
        context = {
            'topics' : topics,
            'session' : session,
        }
        return render(request, 'boardapp/sharedetail.html', context)
    except KeyError:
        return redirect('boardapp:share')
    
def new_write(request): #게시글 목록에서 글쓰기 버튼 클릭 시 쓰기 페이지로 이동
    uid = request.session['id']
    uid = User.objects.get(id = uid)


    # b = Board(id = uid,title=request.POST['title'], content=request.POST['detail'], 
    topics = Topic(writter = uid, subject =request.POST['subject'], message =request.POST['message'], file = request.FILES.get('file')) 
    if topics.subject !="":
        topics.save()

def sharedetail1(request, postid):
    uid = request.session['id']
    uid = User.objects.get(id = uid)
    posts = get_object_or_404(Replys, pk=postid)
    try:
        uid = request.session['id']
        session = User.objects.get(id = uid)
        context = {
            'posts' : posts,
            'session' : session,
        }
        return render(request, 'boardapp/sharedetail1.html', context)
    except KeyError:
        return redirect('boardapp:sharedetail')

    return HttpResponseRedirect(reverse('boardapp:share'))
def new_topic(request):
    # topics = Topic.objects.all()
    # if request.method == 'POST':      
    #     uid = request.session['id']
    #     uid = User.objects.get(id = uid)
        
        # topics = Topic.objects.create(
        #     subject=subject,
        #     message=message,
        #     writter=user
        #     )
        # topics = Topic(writter = uid, subject =request.POST['subject'], message =request.POST['message'], file = request.FILES['file']) 
        # if topics.subject !="":
        #     topics.save()

        # posts = Replys.objects.create(
        #     created_at = timezone.now(),
        #     message = message,
        #     created_by=uid,
        #     updated_by=uid,
        #     updated_at = timezone.now())

    
    return render(request, 'boardapp/new_topic.html')

def new_replys(request):
    posts = Replys.objects.all()
    if request.method == 'POST':
        message = request.POST['message']

        uid = request.session['id']
        uid = User.objects.get(id = uid)

        posts = Replys(created_by = uid, message =request.POST['message'],created_at = timezone.now(),updated_by=uid,
        updated_at = timezone.now()) 
        posts.save()
        # posts = Replys.objects.create(
        #     created_at = timezone.now(),
        #     message = message,
        #     created_by=uid,
        #     updated_by=uid,
        #     updated_at = timezone.now())

        return redirect('boardapp:sharedetail')
    
    return render(request,'boardapp/new_replys.html',{'posts': posts})


# def replys(request, postsid):
#     uid = request.session['id']
#     uid = User.objects.get(id = uid)
#     posts = get_object_or_404(Replys, pk=postsid)
#     try:
#         uid = request.session['id']
#         session = User.objects.get(id = uid)
#         context = {
#             'posts' : posts,
#             'session' : session,
#         }
#         return render(request, 'boardapp/replys.html', context)
#     except KeyError:
#         return redirect('boardapp:share')




# def detail1(request, id): #게시글 제목 선택시 상세 페이지로 이동
#     board1 = Topic.objects.get(id=id)
#     return render(request, 'boardapp/detail1.html', {'boardapp1': board1})

# # def detail(request, postNum): #게시글 제목 선택시 상세 페이지로 이동
# #     board = Board.objects.get(postNum=postNum)
# #     return render(request, 'boardapp/detail.html', {'boardapp': board})    

# def create1_reply(request, id): # 상세 페이지에서 댓글 동록시 submit 처리
#     uid = request.session['id']
#     uid = User.objects.get(id=uid)

#     b = Topic.objects.get(id = id)
#     b.reply1_set.create(writter = uid, message=request.POST['message'], last_updated=timezone.now())
#     return HttpResponseRedirect(reverse('boardapp:detail1', args=(id,)))  

# # def create_reply(request, postNum): # 상세 페이지에서 댓글 동록시 submit 처리
# #     uid = request.session['id']
# #     uid = User.objects.get(id=uid)

# #     b = Board.objects.get(postNum = postNum)
# #     b.reply_set.create(id = uid, comment=request.POST['comment'], rep_date=timezone.now())
# #     return HttpResponseRedirect(reverse('boardapp:detail', args=(postNum,)))  


# def update1(request, board_id1):
#     b = Topic.objects.get(id= board_id1)
#     temp = Topic.objects.get(id= board_id1)
#     if request.method == "POST":
#         b.subject=request.POST['subject']
#         if b.subject == "":
#             b.subject = temp.subject
#         b.message=request.POST['message']
#         if b.message == "":
#             b.message = temp.message
#         b.last_updated=timezone.now()
#         b.save()
#         return HttpResponseRedirect(reverse('boardapp:detail1',args=(board_id1,)))
#     else:
#         b=Topic
#         return render(request, 'boardapp/update1.html', {'boardapp1':b})

# # def update(request, board_id):
# #     b = Board.objects.get(postNum= board_id)
# #     temp = Board.objects.get(postNum= board_id)
# #     if request.method == "POST":
# #         b.title=request.POST['title']
# #         if b.title == "":
# #             b.title = temp.title
# #         b.content=request.POST['detail']
# #         if b.content == "":
# #             b.content = temp.content
# #         b.pub_date=timezone.now()
# #         b.save()
# #         return HttpResponseRedirect(reverse('boardapp:detail',args=(board_id,)))
# #     else:
# #         b=Board
# #         return render(request, 'boardapp/update.html', {'boardapp':b})


# def delete1(request, board_id1):
#     b = Topic.objects.get(id=board_id1)
#     b.delete()
#     return redirect('boardapp:share')

# # def delete(request, board_id):
# #     b = Board.objects.get(postNum=board_id)
# #     b.delete()
# #     return redirect('boardapp:home')

candyprj/templates/boardapp/detail.html
{% extends 'boardapp/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% block content %}
<body>
	<link rel="stylesheet" href="static/bootstrap/css/main.css" />
    <div class="container">
		<h5 class="my-3 border-bottom pb-2">{{ boardapp.postNum }} 번째 스터디 구인 정보</h5>
		<div id="main">
				<article class="post">
					<header>
						<div class="title">
							<h2>{{ boardapp.title }}</h2>
						</div>
						<div class="meta">
							<time class="published">{{ boardapp.pub_date }}</time>
							<a class="author"><span class="name">{{ boardapp.id_id }}</span></a>
						</div>
					</header>
					<hr>
					<p>{{ boardapp.content }}</p>
					<hr>
				</article>
		</div>
		<button type="button" class="btn btn-outline-primary" onclick="location.href='{% url 'boardapp:home' %}'">home</button>
		{%if request.session.id == boardapp.id_id%}
		
		<button type="button" class="btn btn-outline-secondary" onclick="location.href='{% url 'boardapp:update' boardapp.postNum %}'">수정</button>
		<button type="button" class="btn btn-outline-danger" onclick="location.href='{% url 'boardapp:delete' boardapp.postNum %}'">삭제</button>
		{%endif%}

		<form action="{% url 'boardapp:create_reply' boardapp.postNum %}" method="post">
		{% csrf_token %}
		<table class="board_for_read">
			<tbody>
				<br>
				<tr>
					<td class="input-group mb-3" style="text-align:center;">
						<input type="text" name="comment" id="comment" class="form-control" placeholder="댓글" style="width:100%">
					</td>
					<td><input type="submit" value="추가"></td>
				</tr>
			</tbody>
		</table>
		</form>

		<div class="reply_content">
			{% for rep in boardapp.reply_set.all %}
				<span class="reply">{{ rep.comment }} [{{ rep.rep_date|date:'Y-m-d H:i'}}] -{{rep.id}}</span><br>
			{% endfor %}
		</div>
    
</body>
{%endblock%}
</html>

candyprj/templates/boardapp/home.html
{% extends 'boardapp/base.html' %}
{% load board_filter %}
{% block title %}Index page{% endblock %}

{% block content %}
<div class='search' style="float:right; margin:10px;">
    <input id='kw' type='text' placeholder='Search' value="{{kw}}">
    <button type = 'submit' id='btn_search'> 검색 </button>
</div> 

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
			<th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if not board %}
		<tr>
			<td colspan='4' style="text-align:center">
				게시물이 없습니다.

			</td>
		</tr>
		{%else%}
        {%for item in board %}
				<tr>
					<td>{{item.postNum}}</td>
					<td>
						<a style="color:#000000" {%if request.session.id %} href="{% url 'boardapp:detail' item.postNum %}" {%else%} href = '/user/login/' onclick="alertAccess()" {%endif%} >
							{{item.title}}
						</a>
                        <span> [{{ item.reply_set.count }}] </span>
					</td>
					<td>
						<a style="color:#000000" {%if request.session.id %} href="{% url 'userapp:userinfo' item.id_id %}" {%else%} href = '/user/login/' onclick="alertAccess()" {%endif%} >
							{{item.id_id}}
						</a>
					</td>
					<td>{{item.pub_date}}</td>
				</tr>
		{%endfor%}
        {% endif %}
        </tbody>
    </table>
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?kw={{kw}}&page={{ board.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        
        {% for page_number in board.paginator.page_range %}
        {% if page_number >= board.number|add:-5 and page_number <= board.number|add:5 %}    
            {% if page_number == board.number %}
            <li class="page-item active" aria-current="page">
                <a id = 'pageBtn' class="page-link" href="?kw={{kw}}&page={{ page_number }}">{{ page_number }}</a>
                {% comment %} <a id = 'pageBtn' class="page-link" onclick=>{{ page_number }}</a> {% endcomment %}
                <a id='page' style = 'visibility: hidden'>{{page_number}}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a id = 'pageBtn'class="page-link" href="?kw={{kw}}&page={{ page_number }}">{{ page_number }}</a>
                {% comment %} <a id = 'pageBtn'class="page-link">{{ page_number }}</a> {% endcomment %}
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board.has_next %}
        <li class="page-item">
            <a class="page-link" href="?kw={{kw}}&page={{ board.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <a class="btn btn-primary" {%if request.session.id %} href="{% url 'boardapp:write' %}" {%else%} href = '/user/login/' onclick="alertAccess()" {%endif%}>
        질문 등록하기
    </a>



    <script>
        function alertAccess() {
            alert("로그인 후 이용 가능합니다.")
        }
        document.getElementById("btn_search").addEventListener("click", () => {


            key = document.getElementById('kw').value
            page = document.getElementById('page').text
            
            location.href = '?kw=' +  key + '&page=1'
            

            
          });
    </script>
{% endblock  %}

candyprj/templates/boardapp/index.html
{% extends 'boardapp/base.html' %}
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ListPage</title>
</head>
<style type="text/css">
        thead {
            background-color:#cecece;
        }

        .content {
            max-width:500px;
            margin: auto;
            padding:10px;
        }

        .header {
            text-align: center;
        }

        .board {
            width: 100%
        }

        .even_bgcolor {
            background-color:#e8efff;
        }

        .pagination {
            display: flex;           
        }

        .current {
            font-weight: bold;
        }

        a {
            text-decoration: none;
            text-align: center;
        }

        .abutton {
            background-color: #e6e6ff;
            color: #7b7b7b;
            font-size: small;
        }

    </style>
<body>
    <div class="content">
        <div class="header">
            <h2>{{ title }}</h2>
        </div>
        <div style="text-align:right">
            <a href="{% url 'boardapp:write' %}">글쓰기</a>
        </div>

        <div style="height:280px;">
            <table class="board">
                <thead>
                    <tr class="header">
                        <th style="width:10%;">순번</th>
                        <th style="width:60%">제목</th>
                        <th style="width:30%">작성일자</th>
                    </tr>
                </thead>
                <tbody>
                {% if board_list %}
                    {% for data in board_list %}
                    <tr class="{% cycle '' 'even_bgcolor' %}">
                        <td style="text-align:center;">{{ forloop.counter }}</td>
                        <td>
                            <a href="{% url 'boardapp:detail' data.id %}">
                                {{ data.title }}
                            </a>
                        </td>
                        <td>{{ data.pub_date|date:'Y-m-d' }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td>작성된 게시글이 없습니다.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <div style="text-align:center">
            <div class="pagination">
            
                <div style="width:35%; margin: 5px;">
                {% if board_list.has_previous %}
                    <a class="abutton" href="?page=1">맨 앞으로</a>
                    <a class="abutton" href="?page={{ board_list.previous_page_number }}">이전</a>
                {% endif %}
                </div>

                <div style="width:30%; margin: 5px;">
                {% for page in board_list.paginator.page_range %}
                    {% if page >= board_list.number|add:-2 and page <= board_list.number|add:2 %}
                    <span class="{% if page == board_list.number %}current{% endif %}">
                        <a href="?page={{ page }}">{{ page}}</a>
                    </span>
                    {% elif page >= board_list.number|add:-3 and page <= board_list.number|add:3 %}
                        ..
                    {% endif %}
                {% endfor %}
                </div>

                <div style="width:35%; margin: 5px;">
                {% if board_list.has_next %}
                    <a class="abutton" href="?page={{ board_list.next_page_number }}">다음</a>
                    <a class="abutton" href="?page={{ board_list.paginator.num_pages }}">맨 뒤로</a>
                {% endif %}
                </div>

            </div>  
        </div> 
    </div>
</body>
</html>  

candyprj/templates/boardapp/new_replys.html
{% extends  'boardapp/sharebase.html' %}

{% block title %} writting {% endblock %}


{% block boardhead %}
    <form method ="post">
        {% csrf_token %}
       
        <!-- writting title -->
        <div class="form-group">
            <label for="id_message"> 댓글 </label>
            <input type="text" class="form-control" id="id_message" name="message" value= "{{ posts.message }}"/>
        </div>

        {% comment %} <div class="form-group">
            <label for="id_message">내용</label>
            <textarea class="form-control" id="id_message" name="message" rows="5"></textarea>
        </div> {% endcomment %}

        <button type="submit" class="btn btn-success">게시</button>


</form>
{% endblock %}

candyprj/templates/boardapp/share.html
{% extends 'boardapp/sharebase.html' %}

{% block boardhead %}

    <table class="table">
        <thead  class="thead-inverse">
            <tr>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일자</th>
            </tr>
        </thead>

        <tbody>
            {% for topic in topics %}
            <tr>
                <td>{{topic.writter_id}}</td>
                <td><a href="{% url 'boardapp:sharedetail' topicid=topic.id %}">{{ topic.subject }}</a></td>
                {% comment %} <td>
                    <a style="color:#000000" {%if request.session.id %} href="{% url 'boardapp:sharedetail' topic.writter %}" {%else%} href = '/user/login/' onclick="alertAccess()" {%endif%} >
                        {{topic.subject}}
                    </a>
                </td>  {% endcomment %}
                <td>{{topic.last_updated}}</td>
            </tr>
            {% endfor %}

        </tbody>
      
    </table>

    <div class="mb-4">
        <a href='/board/new/' class="btn btn-info"><b>글 작성</b></a>
    </div> 

{% endblock %}

candyprj/templates/boardapp/sharedetail.html
{% extends  'boardapp/sharedetailview.html' %} 

{% block boardhead %}
<header class="masthead">
    <div class="container px-4 px-lg-5 h-100">
        <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
<div class="col-lg-8 align-self-end">
    <h1 class="text-white font-weight-bold">{{ topics.subject }}</h1>
    {% comment %} <h1 class="text-white font-weight-bold">{{ topics.message }}</h1> {% endcomment %}
    <hr class="divider" />
</div>

<div class="col-lg-8 align-self-baseline">
    <p class="text-white-75 mb-5">{{topics.message}}</p>
    {% if blog.images %}
                <img src="{{ topics.file.url }}" width="500" height="500">
    {% endif %}
    <br>
    {% comment %} <a href="{% url 'boardapp:update' boardapp.postNum %}">수정</a>
	<a href="{% url 'boardapp:delete' boardapp.postNum %}">삭제</a> {% endcomment %}
    <a class="btn btn-primary btn-xl" href='/board/new'>글 작성하기</a>
    {% comment %} <a class="btn btn-primary btn-xl" href='/board/replys'>댓글 쓰기</a> {% endcomment %}
    
</div>

 {% comment %} <div class="col-lg-8 align-self-baseline">
    <p class="text-white-75 mb-5"><input type ="text" class ="title" name = "topics.subject" value= "{{ topics.subject }}" readonly/></p>
    <textarea class ="content" name= "topics.message" readonly>{{topics.message}} </textarea>
</div>  {% endcomment %}
{% endblock %}

candyprj/templates/boardapp/signup.html
{% extends 'boardapp/base.html' %}

{% block title %}Index page{% endblock %}

{% block content %}
<style>
	.card {
		padding: 10px;		
	}

	.card h3 {
		font-family: none;
	} 
</style>
<div class="container">
    <div class="row mt-5">
        <div class="col-8" text-center>
            <h2>회원가입</h2>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-8">
            <form method="post" action="{% url 'userapp:login' %}">
                {% csrf_token %}
                아이디 : <input type="text" class="form-control" name="id"><br><br>
                비밀번호 : <input type="text" class="form-control" name="pw"><br><br>
                이름 : <input type="text" class="form-control" name="name"><br><br>
                생일 : <input type="text" class="form-control" name="birth"><br><br>
                메일 : <input type="text" class="form-control" name="mail"><br><br>
                <button id='signupBtn' class="from-control" onclick="signup()"  >회원가입</button>
            </form>
        </div>
    </div>
</div>



<script>
    function signup(){
        alert("회원가입되었습니다.")
    }
</script>

{% endblock  %}